apiVersion: v1
kind: Service
metadata:
name: django-messaging-service
labels:
app: django-app
spec:

The service type remains ClusterIP, accessible internally
type: ClusterIP
selector:
app: django-app
# 🎯 INITIAL TRAFFIC ROUTING: Point to the 'blue' (old) version
version: blue
ports:
- protocol: TCP
port: 80
targetPort: 8000